# Generated by Django 5.0.7 on 2024-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(null=True),
        ),
    ]
